version: "3"

services:
  api:
    build: ./
    image: africancsirt
    command:  uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    networks:
      - africancsirt_network

networks:
  africancsirt_network:
    driver: bridge
